---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm install -g bower yarn phantomjs-prebuilt
  - yarn --version
  - bower --version
  - phantomjs --version

install:
  - yarn install

script:
  - ember try $EMBER_TRY_SCENARIO test
